### ISSUE TITLE
4 high severity vulnerabilities in dependency

### ISSUE THREAD

**Issue by DominikTV** [aalfiann/parallel-http-request#1]
When running `npm audit fix`

```cmd
up to date, audited 90 packages in 888ms

3 packages are looking for funding
  run `npm fund` for details
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
No fix available
node_modules/async
  form-data  0.0.2 - 1.0.0-rc4
  Depends on vulnerable versions of async
  node_modules/unirest/node_modules/form-data
    unirest  >=0.2.8
    Depends on vulnerable versions of form-data
    node_modules/unirest
      parallel-http-request  *
      Depends on vulnerable versions of unirest
      node_modules/parallel-http-request

4 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

**Comment by aalfiann** [comment]
I'll take a look at this.. Thank you

**Comment by aalfiann** [comment]
I just read correctly to your log, that's problem is at  async library, not in parallel-http-request.

`Severity: high  
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25`

And also to make sure this library parallel-http-request is safe,  
I have test this  with using old NodeJS version 

Tested in NodeJS 14
![](https://i.imgur.com/IFek6SV.png)

Tested in NodeJS 10
![](https://i.imgur.com/rPGrKpk.png)
